{
    'name': "Automatization Service Center",
    'summary': "Module for odoo-course",
    'license': 'LGPL-3',
    'author': "Dicantnik",
    'website': "https://example.com",
    'category': 'Uncategorized',
    'version': '17.0.1.0.0',
    'depends': ['base', ],
    'external_dependencies': {},
    # always loaded
    'data': [
        'security/service_center_groups.xml',
        'security/service_center_security.xml',
        'security/ir.model.access.csv',
        'views/service_center_service_views.xml',
        'views/service_center_menus.xml',
        'views/service_center_res_partner_views.xml',
        'views/service_center_car_views.xml',
        'views/service_center_lead_views.xml',
        'views/service_center_engineer_views.xml',
        'views/service_center_slot_views.xml',
        'views/service_center_time_table_views.xml',
        'views/service_center_overview_result_views.xml',
        'views/service_center_engineer_calendar_views.xml',
        'wizard/service_center_list_leads_views.xml',
        'data/service_center_service_data.xml',
        'data/service_center_engineer_data.xml',
        'reports/overview_result_views.xml',
        'reports/overview_result_template.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/service_center_car_demo.xml',
        'demo/service_center_lead_demo.xml',
        'demo/service_center_service_demo.xml',
        'demo/service_center_overview_result_demo.xml',
        'demo/service_center_time_table_demo.xml',
        'demo/service_center_engineer_calendar_demo.xml',
        'demo/call_func_demo.xml',
    ],
    'images': ['static/description/banner.png', 'static/description/icon.png'],
    'live_test_url': 'https://demo.example.com',
    'price': 0.0,
    'currency': 'EUR',
    'support': 'support@example.com',
    'application': False,
    'installable': True,
    'auto_install': False,

}
